Feature/adjust button
algopainter/algopainter-website pull request #4
Opened 2021-06-07 20:10 UTC by FranBernardo

adjust the buy button components responsive and removed the white space on the right side

2021-06-08 18:24 UTC, jpauloamartins requested changes

2021-06-08 18:24 UTC, jpauloamartins commented on src/pages/StarterPage.vue
> +              "
Não é possível utilizar `href` para o link?

2021-06-08 18:24 UTC, jpauloamartins commented on src/pages/StarterPage.vue
> +      <!--  <div class="degrade"></div> -->
Remover código comentado.

2021-06-08 18:24 UTC, jpauloamartins commented on src/pages/StarterPage.vue
> +                "
Não é possível utilizar `href` para o link?

2021-06-08 18:24 UTC, jpauloamartins commented on src/pages/StarterPage.vue
> +/*.degrade {
Remover código comentado.

2021-06-08 18:27 UTC, FranBernardo commented on src/pages/StarterPage.vue
> +      <!--  <div class="degrade"></div> -->
certo, vou retirar o comentário.

2021-06-08 18:28 UTC, FranBernardo commented on src/pages/StarterPage.vue
> +/*.degrade {
cento.

2021-06-08 18:29 UTC, FranBernardo commented on src/pages/StarterPage.vue
> +                "
com o href seria melhor?

2021-06-09 13:12 UTC, jpauloamartins approved these changes

2021-06-09 13:13 UTC, merged